server:
  port: 8061

dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://192.168.118.128:2181
    # 读者请自行更改zookeeper地址
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 30003
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000

